# Generated by Django 3.1.6 on 2021-02-22 18:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_extensions.db.fields
import django_resized.forms
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(help_text=' প্রকল্পের শিরোনাম দিন ', max_length=100)),
                ('description', tinymce.models.HTMLField(blank=True, help_text=' বর্ন্না লিখুন ')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from='project_title')),
                ('external_video_storage', models.URLField(blank=True, help_text='*Youtube embeded link only')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, help_text='Picture *Automatic convert into 500*500 pixel', keep_meta=True, quality=0, size=[500, 500], upload_to='images/')),
                ('default', models.BooleanField(default=False)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ebaybdApp.projects')),
            ],
        ),
    ]
